/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicRouteImport } from './routes/topic'
import { Route as ResultRouteImport } from './routes/result'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DateRouteImport } from './routes/date'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalismanThemeIndexRouteImport } from './routes/talisman-theme/index'
import { Route as InformationIndexRouteImport } from './routes/information/index'
import { Route as TalismanThemeThemeRouteImport } from './routes/talisman-theme/$theme'
import { Route as ReportTopicRouteImport } from './routes/report/$topic'
import { Route as InformationTimeRouteImport } from './routes/information/time'
import { Route as InformationNicknameRouteImport } from './routes/information/nickname'
import { Route as InformationGenderRouteImport } from './routes/information/gender'
import { Route as InformationBirthRouteImport } from './routes/information/birth'

const TopicRoute = TopicRouteImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalismanThemeIndexRoute = TalismanThemeIndexRouteImport.update({
  id: '/talisman-theme/',
  path: '/talisman-theme/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationIndexRoute = InformationIndexRouteImport.update({
  id: '/information/',
  path: '/information/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalismanThemeThemeRoute = TalismanThemeThemeRouteImport.update({
  id: '/talisman-theme/$theme',
  path: '/talisman-theme/$theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTopicRoute = ReportTopicRouteImport.update({
  id: '/report/$topic',
  path: '/report/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationTimeRoute = InformationTimeRouteImport.update({
  id: '/information/time',
  path: '/information/time',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationNicknameRoute = InformationNicknameRouteImport.update({
  id: '/information/nickname',
  path: '/information/nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationGenderRoute = InformationGenderRouteImport.update({
  id: '/information/gender',
  path: '/information/gender',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationBirthRoute = InformationBirthRouteImport.update({
  id: '/information/birth',
  path: '/information/birth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/date': typeof DateRoute
  '/language': typeof LanguageRoute
  '/result': typeof ResultRoute
  '/topic': typeof TopicRoute
  '/information/birth': typeof InformationBirthRoute
  '/information/gender': typeof InformationGenderRoute
  '/information/nickname': typeof InformationNicknameRoute
  '/information/time': typeof InformationTimeRoute
  '/report/$topic': typeof ReportTopicRoute
  '/talisman-theme/$theme': typeof TalismanThemeThemeRoute
  '/information': typeof InformationIndexRoute
  '/talisman-theme': typeof TalismanThemeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/date': typeof DateRoute
  '/language': typeof LanguageRoute
  '/result': typeof ResultRoute
  '/topic': typeof TopicRoute
  '/information/birth': typeof InformationBirthRoute
  '/information/gender': typeof InformationGenderRoute
  '/information/nickname': typeof InformationNicknameRoute
  '/information/time': typeof InformationTimeRoute
  '/report/$topic': typeof ReportTopicRoute
  '/talisman-theme/$theme': typeof TalismanThemeThemeRoute
  '/information': typeof InformationIndexRoute
  '/talisman-theme': typeof TalismanThemeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/date': typeof DateRoute
  '/language': typeof LanguageRoute
  '/result': typeof ResultRoute
  '/topic': typeof TopicRoute
  '/information/birth': typeof InformationBirthRoute
  '/information/gender': typeof InformationGenderRoute
  '/information/nickname': typeof InformationNicknameRoute
  '/information/time': typeof InformationTimeRoute
  '/report/$topic': typeof ReportTopicRoute
  '/talisman-theme/$theme': typeof TalismanThemeThemeRoute
  '/information/': typeof InformationIndexRoute
  '/talisman-theme/': typeof TalismanThemeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera'
    | '/date'
    | '/language'
    | '/result'
    | '/topic'
    | '/information/birth'
    | '/information/gender'
    | '/information/nickname'
    | '/information/time'
    | '/report/$topic'
    | '/talisman-theme/$theme'
    | '/information'
    | '/talisman-theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera'
    | '/date'
    | '/language'
    | '/result'
    | '/topic'
    | '/information/birth'
    | '/information/gender'
    | '/information/nickname'
    | '/information/time'
    | '/report/$topic'
    | '/talisman-theme/$theme'
    | '/information'
    | '/talisman-theme'
  id:
    | '__root__'
    | '/'
    | '/camera'
    | '/date'
    | '/language'
    | '/result'
    | '/topic'
    | '/information/birth'
    | '/information/gender'
    | '/information/nickname'
    | '/information/time'
    | '/report/$topic'
    | '/talisman-theme/$theme'
    | '/information/'
    | '/talisman-theme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  DateRoute: typeof DateRoute
  LanguageRoute: typeof LanguageRoute
  ResultRoute: typeof ResultRoute
  TopicRoute: typeof TopicRoute
  InformationBirthRoute: typeof InformationBirthRoute
  InformationGenderRoute: typeof InformationGenderRoute
  InformationNicknameRoute: typeof InformationNicknameRoute
  InformationTimeRoute: typeof InformationTimeRoute
  ReportTopicRoute: typeof ReportTopicRoute
  TalismanThemeThemeRoute: typeof TalismanThemeThemeRoute
  InformationIndexRoute: typeof InformationIndexRoute
  TalismanThemeIndexRoute: typeof TalismanThemeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topic': {
      id: '/topic'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof TopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date': {
      id: '/date'
      path: '/date'
      fullPath: '/date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talisman-theme/': {
      id: '/talisman-theme/'
      path: '/talisman-theme'
      fullPath: '/talisman-theme'
      preLoaderRoute: typeof TalismanThemeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/': {
      id: '/information/'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talisman-theme/$theme': {
      id: '/talisman-theme/$theme'
      path: '/talisman-theme/$theme'
      fullPath: '/talisman-theme/$theme'
      preLoaderRoute: typeof TalismanThemeThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$topic': {
      id: '/report/$topic'
      path: '/report/$topic'
      fullPath: '/report/$topic'
      preLoaderRoute: typeof ReportTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/time': {
      id: '/information/time'
      path: '/information/time'
      fullPath: '/information/time'
      preLoaderRoute: typeof InformationTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/nickname': {
      id: '/information/nickname'
      path: '/information/nickname'
      fullPath: '/information/nickname'
      preLoaderRoute: typeof InformationNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/gender': {
      id: '/information/gender'
      path: '/information/gender'
      fullPath: '/information/gender'
      preLoaderRoute: typeof InformationGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/birth': {
      id: '/information/birth'
      path: '/information/birth'
      fullPath: '/information/birth'
      preLoaderRoute: typeof InformationBirthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  DateRoute: DateRoute,
  LanguageRoute: LanguageRoute,
  ResultRoute: ResultRoute,
  TopicRoute: TopicRoute,
  InformationBirthRoute: InformationBirthRoute,
  InformationGenderRoute: InformationGenderRoute,
  InformationNicknameRoute: InformationNicknameRoute,
  InformationTimeRoute: InformationTimeRoute,
  ReportTopicRoute: ReportTopicRoute,
  TalismanThemeThemeRoute: TalismanThemeThemeRoute,
  InformationIndexRoute: InformationIndexRoute,
  TalismanThemeIndexRoute: TalismanThemeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
